name: Web client issue
description: Report an issue with the web client (audio client)
title: "[BUG: Web client] "
labels: [ "status: needs triage", "type: bug" ]
assignees:
  - xaanndeer
  - LBeukennoot
body:
  - type: dropdown
    attributes:
      label: Browser
      multiple: false
      options:
        - Google Chrome
        - Opera
        - Opera GX
        - Mozilla Firefox
        - Microsoft Edge
        - Brave
        - Safari
    validations:
      required: true

  - type: textarea
    attributes:
      label: Describe the bug
      description: A clear description of what the issue is.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected behavior
      description: A clear description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to reproduce
      description: This may include screenshots, a video, or detailed instructions to help reconstruct the issue.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Other
      description: Add any other context about the problem here.
    validations:
      required: false

  - type: markdown
    attributes:
      value: Before submitting this issue, please ensure there isn't already an issue regarding this.